import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireMember } from "@/lib/session";

/**
 * GET /api/rewards
 * Get all rewards for the current household
 */
export async function GET() {
  try {
    const member = await requireMember();

    const [rewards, level, redemptions] = await Promise.all([
      prisma.householdReward.findMany({
        where: {
          householdId: member.householdId,
          isActive: true,
        },
        orderBy: { pointsCost: "asc" },
      }),
      prisma.memberLevel.findUnique({
        where: { memberId: member.id },
        select: { xp: true },
      }),
      prisma.rewardRedemption.findMany({
        where: { memberId: member.id },
        select: { reward: { select: { pointsCost: true } } },
      }),
    ]);

    const spentPoints = redemptions.reduce((sum, r) => sum + r.reward.pointsCost, 0);
    const availablePoints = (level?.xp ?? 0) - spentPoints;

    return NextResponse.json({
      rewards,
      stats: {
        totalXp: level?.xp ?? 0,
        spentPoints,
        availablePoints,
      },
    });
  } catch (error) {
    console.error("GET /api/rewards error:", error);

    if (error instanceof Error && error.message === "Not a member of any household") {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    return NextResponse.json({ error: "Error fetching rewards" }, { status: 500 });
  }
}

/**
 * POST /api/rewards
 * Deprecated - rewards are now generated by AI via /api/ai/generate-rewards.
 */
export async function POST() {
  return NextResponse.json(
    { error: "Las recompensas ahora se generan automáticamente. Usa /api/ai/generate-rewards." },
    { status: 410 }
  );
}
